gems: [jekyll-paginate, bourbon, neat]

timezone: America/Los_Angeles
title: UCSC News Archives
permalink: /:year/:month/:title/
baseurl: /

source: ./source
destination: ./build
exclude: ['./source/jekyll-metadata']

paginate_path: /page/:num
paginate: 10
